# Generated by Django 6.0.3 on 2026-04-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='arabic_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
