# Generated by Django 5.2.13 on 2026-04-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='extra_Data',
            new_name='extra_data',
        ),
    ]
