# Generated by Django 6.0.3 on 2026-04-08 22:40

from django.db import migrations

def create_initial_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="0",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )

    PeriodicTask.objects.get_or_create(
        name="Daily Contract Deadline Audit",
        defaults={
            'task': 'apps.notifications.tasks.check_upcoming_deadlines',
            'crontab': schedule,
        }
    )

class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0001_initial'), 
        ('django_celery_beat', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_initial_task),
    ]